### PR TITLE
correction for the bug due to the name of the function end()

### PR DESCRIPTION
**Pull request by LucasMahieu**
This is the pull request solving the issues #61  "publish error in "end()" function".
Juste rename the begin() and end() function to begin_frame() and end_frame().

### CODE REVIEW

**Comment by Overdrivr** [comment]
Thanks for this PR

Could you replace `begin` by `begin_frame` and `end` by `end_frame` in the tests as well ?

**Comment by Overdrivr** [comment]
Could you rebase the commits into a single one ? 
Use message for this commit

```
Rename end() function to avoid potential duplicate with linker symbol
```

To do that, rebase against laster master commit
```
git rebase -i 2476df8
```
This will open a text file with all 4 commits. prefix the first commit with `reword` and the others with `fixup`. Save the file and close it.

Git will then open a second text file with the commit message for the first commit. Replace it with the message provided above here. Save the file, close it.

Rebase should complete fine at this point.

Do a force push to push the changes to this remote repo, with this command

```
git push origin end_bug --force
```
I'll merge the PR afterwards

Thanks !

**Comment by LucasMahieu** [comment]
This is done, thanks for your attention about this PR
----------------------------------
Lucas MAHIEU
lucas.mahieu@icloud.com

**Comment by Overdrivr** [comment]
There is something weird, the modifications in the test files are gone, are you sure the rebase executed properly ?

**Comment by LucasMahieu** [comment]
I did exactly what your last mail explained.
I will see the problem and push again.
----------------------------------
Lucas MAHIEU
lucas.mahieu@icloud.com

**Comment by Overdrivr** [comment]
It's strange, rebasing should never drop commits like that

**Comment by LucasMahieu** [comment]
is it better now ?
I pushed the right version 
----------------------------------
Lucas MAHIEU
lucas.mahieu@icloud.com

**Comment by Overdrivr** [comment]
Code is good, but we're back to square one for the git history.

I don't know why you're getting those commit messages `Merge branch 'end_bug' of github.com:LucasMahieu/Telemetry into end_bug`. 

It seems that there were differences between your local version of end_bug and the remote version (the one on github.com), and git had to make a non fast-forward merge.

**Comment by LucasMahieu** [comment]
Yes, I noticed this marge, and i don’t understand the reason … 
——————————
Lucas MAHIEU
lucas.mahieu@icloud.com

**Comment by Overdrivr** [comment]
Did you make a `git pull` after the rebase ?

**Comment by LucasMahieu** [comment]
euh.. Oh yes, because git did’t want that I push and tell me to pull before push. I think this is the reason. I should have make a "push —force"
----------------------------------
Lucas MAHIEU
lucas.mahieu@icloud.com

**Comment by Overdrivr** [comment]
Allright good, please rebase again but force push this time. 

This `pull` is why you lost the latest modifications I think

**Comment by LucasMahieu** [comment]
Can you tel me if this history is good enough for you ? 
----------------------------------
Lucas MAHIEU
lucas.mahieu@icloud.com

**Comment by Overdrivr** [comment]
Damn, the last commit was lost again. I really don't know how this is possible, git is particularly good at ensuring that no matter what you do, code changes should never be lost.

Just push the changes in another commit and I will merge.
I wanted to keep history clean but whatever

**Comment by LucasMahieu** [comment]
I think it is good right now ?
I really don’t understand too why, but I forced and marge the two last commit.
It should be good now.

----------------------------------
Lucas MAHIEU
lucas.mahieu@icloud.com

**Comment by Overdrivr** [comment]
Can you go on Gitter right now ? It's still not good

**Pull request merged**
